// <auto-generated />
using System;
using LiturgiekStatistiek.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiturgiekStatistiek.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611205348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ChangeHistory");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DenominationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationDetail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Modality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DenominationId");

                    b.ToTable("Congregations");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ContentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleNl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemList")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ListDefinitions");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ListDefinitionId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DenominationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DenominationId");

                    b.ToTable("Preachers");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SavedQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QueryParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SavedQueries");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BibleTranslationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BroadcastUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ChurchCalendarSundayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("HasBeamerLiturgy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerTexts")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerTextsAndSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadingService")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MusicalAccompanimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PreacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadSermonBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SermonText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SermonTheme")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SpecialOccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.HasIndex("ChurchCalendarSundayId");

                    b.HasIndex("CongregationId");

                    b.HasIndex("Date");

                    b.HasIndex("MusicalAccompanimentId");

                    b.HasIndex("PreacherId");

                    b.HasIndex("SpecialOccasionId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceBundle", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceId", "BundleId");

                    b.HasIndex("BundleId");

                    b.ToTable("ServiceBundles");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementType")
                        .HasColumnType("int");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ScriptureReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("ServiceId", "Position");

                    b.ToTable("ServiceElements");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SongNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceElementId");

                    b.HasIndex("BundleId", "SongNumber");

                    b.ToTable("ServiceElementSongs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceMetadata");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfVerses")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("BundleId", "Number")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceElementSongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerseLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceElementSongId");

                    b.ToTable("SongVerses");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Denomination")
                        .WithMany()
                        .HasForeignKey("DenominationId");

                    b.Navigation("Denomination");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListItem", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListDefinition", "ListDefinition")
                        .WithMany("Items")
                        .HasForeignKey("ListDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListDefinition");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Denomination")
                        .WithMany()
                        .HasForeignKey("DenominationId");

                    b.Navigation("Denomination");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "BibleTranslation")
                        .WithMany()
                        .HasForeignKey("BibleTranslationId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "ChurchCalendarSunday")
                        .WithMany()
                        .HasForeignKey("ChurchCalendarSundayId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Congregation", "Congregation")
                        .WithMany("Services")
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "MusicalAccompaniment")
                        .WithMany()
                        .HasForeignKey("MusicalAccompanimentId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Preacher", "Preacher")
                        .WithMany("Services")
                        .HasForeignKey("PreacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "SpecialOccasion")
                        .WithMany()
                        .HasForeignKey("SpecialOccasionId");

                    b.Navigation("BibleTranslation");

                    b.Navigation("ChurchCalendarSunday");

                    b.Navigation("Congregation");

                    b.Navigation("MusicalAccompaniment");

                    b.Navigation("Preacher");

                    b.Navigation("SpecialOccasion");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceBundle", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Bundles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Elements")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceElement", "ServiceElement")
                        .WithMany("Songs")
                        .HasForeignKey("ServiceElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("ServiceElement");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceMetadata", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Metadata")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Song", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongVerse", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", "ServiceElementSong")
                        .WithMany("Verses")
                        .HasForeignKey("ServiceElementSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceElementSong");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListDefinition", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bundles");

                    b.Navigation("Elements");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.Navigation("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
