// <auto-generated />
using System;
using LiturgiekStatistiek.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiturgiekStatistiek.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710212700_AddSongSungInFullAndTemplateDefaultBundle")]
    partial class AddSongSungInFullAndTemplateDefaultBundle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.BibleBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("VerseCountsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ordinal")
                        .IsUnique();

                    b.ToTable("BibleBooks");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.BibleBookTranslationName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BibleBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TranslationAbbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.ToTable("BibleBookTranslationNames");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ChangeHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ChangeHistory");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DenominationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationDetail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Modality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DenominationId");

                    b.ToTable("Congregations");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ContentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TitleNl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemList")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ListDefinitions");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LiturgicalElementType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ListDefinitionId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DenominationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DenominationId");

                    b.ToTable("Preachers");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ReadingReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BibleBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Chapter")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VerseEnd")
                        .HasColumnType("int");

                    b.Property<int?>("VerseStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.HasIndex("ServiceElementId", "Position");

                    b.ToTable("ReadingReferences");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.RecentSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("RecentSearches");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SavedQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QueryParameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SavedQueries");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SermonTextReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BibleBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Chapter")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VerseEnd")
                        .HasColumnType("int");

                    b.Property<int?>("VerseStart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BibleBookId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SermonTextReferences");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BroadcastUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ChurchCalendarSundayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("HasBeamerLiturgy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerTexts")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerTextsAndSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadingService")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MusicalAccompanimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("PreacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadSermonBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SermonText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SermonTheme")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("SpecialOccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChurchCalendarSundayId");

                    b.HasIndex("CongregationId");

                    b.HasIndex("Date");

                    b.HasIndex("MusicalAccompanimentId");

                    b.HasIndex("PreacherId");

                    b.HasIndex("SpecialOccasionId");

                    b.HasIndex("Status");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceBundle", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceId", "BundleId");

                    b.HasIndex("BundleId");

                    b.ToTable("ServiceBundles");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BibleTranslationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElementType")
                        .HasColumnType("int");

                    b.Property<bool>("IsBeurtzang")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("PerformerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ScriptureReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BibleTranslationId");

                    b.HasIndex("LabelId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ServiceId", "Position");

                    b.ToTable("ServiceElements");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<Guid>("ServiceElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SongNumber")
                        .HasColumnType("int");

                    b.Property<bool>("SungInFull")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ServiceElementId");

                    b.HasIndex("BundleId", "Section", "SongNumber");

                    b.ToTable("ServiceElementSongs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceMetadata");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CongregationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DefaultBibleTranslationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultSongBundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DenominationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasBeamerLiturgy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerSongs")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeamerTexts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadingService")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MusicalAccompanimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OccasionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeOfDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CongregationId");

                    b.HasIndex("DefaultBibleTranslationId");

                    b.HasIndex("DefaultSongBundleId");

                    b.HasIndex("DenominationId");

                    b.HasIndex("MusicalAccompanimentId");

                    b.HasIndex("OccasionId");

                    b.ToTable("ServiceTemplates");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceTemplateElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ElementType")
                        .HasColumnType("int");

                    b.Property<string>("FixedScriptureReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsBeurtzang")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PerformerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ServiceTemplateId", "Position");

                    b.ToTable("ServiceTemplateElements");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BundleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfVerses")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("BundleId", "Section", "Number")
                        .IsUnique();

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongCatalogVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SongId", "Number")
                        .IsUnique();

                    b.ToTable("SongCatalogVerses");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceElementSongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerseLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceElementSongId");

                    b.ToTable("SongVerses");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.BibleBookTranslationName", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.BibleBook", "BibleBook")
                        .WithMany("TranslationNames")
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleBook");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Denomination")
                        .WithMany()
                        .HasForeignKey("DenominationId");

                    b.Navigation("Denomination");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListItem", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListDefinition", "ListDefinition")
                        .WithMany("Items")
                        .HasForeignKey("ListDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListDefinition");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Denomination")
                        .WithMany()
                        .HasForeignKey("DenominationId");

                    b.Navigation("Denomination");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ReadingReference", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.BibleBook", "BibleBook")
                        .WithMany()
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceElement", "ServiceElement")
                        .WithMany("ReadingReferences")
                        .HasForeignKey("ServiceElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleBook");

                    b.Navigation("ServiceElement");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SermonTextReference", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.BibleBook", "BibleBook")
                        .WithMany()
                        .HasForeignKey("BibleBookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("SermonTextReferences")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleBook");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "ChurchCalendarSunday")
                        .WithMany()
                        .HasForeignKey("ChurchCalendarSundayId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Congregation", "Congregation")
                        .WithMany("Services")
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "MusicalAccompaniment")
                        .WithMany()
                        .HasForeignKey("MusicalAccompanimentId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Preacher", "Preacher")
                        .WithMany("Services")
                        .HasForeignKey("PreacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "SpecialOccasion")
                        .WithMany()
                        .HasForeignKey("SpecialOccasionId");

                    b.Navigation("ChurchCalendarSunday");

                    b.Navigation("Congregation");

                    b.Navigation("MusicalAccompaniment");

                    b.Navigation("Preacher");

                    b.Navigation("SpecialOccasion");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceBundle", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Bundles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "BibleTranslation")
                        .WithMany()
                        .HasForeignKey("BibleTranslationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Elements")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BibleTranslation");

                    b.Navigation("Label");

                    b.Navigation("Performer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceElement", "ServiceElement")
                        .WithMany("Songs")
                        .HasForeignKey("ServiceElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("ServiceElement");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceMetadata", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Service", "Service")
                        .WithMany("Metadata")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceTemplate", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Congregation", "Congregation")
                        .WithMany()
                        .HasForeignKey("CongregationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "DefaultBibleTranslation")
                        .WithMany()
                        .HasForeignKey("DefaultBibleTranslationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "DefaultSongBundle")
                        .WithMany()
                        .HasForeignKey("DefaultSongBundleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Denomination")
                        .WithMany()
                        .HasForeignKey("DenominationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "MusicalAccompaniment")
                        .WithMany()
                        .HasForeignKey("MusicalAccompanimentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Occasion")
                        .WithMany()
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Congregation");

                    b.Navigation("DefaultBibleTranslation");

                    b.Navigation("DefaultSongBundle");

                    b.Navigation("Denomination");

                    b.Navigation("MusicalAccompaniment");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceTemplateElement", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceTemplate", "ServiceTemplate")
                        .WithMany("Elements")
                        .HasForeignKey("ServiceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Performer");

                    b.Navigation("ServiceTemplate");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Song", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ListItem", "Bundle")
                        .WithMany()
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongCatalogVerse", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.Song", "Song")
                        .WithMany("Verses")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.SongVerse", b =>
                {
                    b.HasOne("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", "ServiceElementSong")
                        .WithMany("Verses")
                        .HasForeignKey("ServiceElementSongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceElementSong");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.BibleBook", b =>
                {
                    b.Navigation("TranslationNames");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Congregation", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ListDefinition", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Preacher", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Service", b =>
                {
                    b.Navigation("Bundles");

                    b.Navigation("Elements");

                    b.Navigation("Metadata");

                    b.Navigation("SermonTextReferences");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElement", b =>
                {
                    b.Navigation("ReadingReferences");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceElementSong", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.ServiceTemplate", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LiturgiekStatistiek.Domain.Entities.Song", b =>
                {
                    b.Navigation("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
