FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["LiturgiekStatistiek.Api/LiturgiekStatistiek.Api.csproj", "LiturgiekStatistiek.Api/"]
COPY ["LiturgiekStatistiek.Application/LiturgiekStatistiek.Application.csproj", "LiturgiekStatistiek.Application/"]
COPY ["LiturgiekStatistiek.Domain/LiturgiekStatistiek.Domain.csproj", "LiturgiekStatistiek.Domain/"]
COPY ["LiturgiekStatistiek.Infrastructure/LiturgiekStatistiek.Infrastructure.csproj", "LiturgiekStatistiek.Infrastructure/"]
COPY ["NuGet.Config", "."]
RUN dotnet restore "LiturgiekStatistiek.Api/LiturgiekStatistiek.Api.csproj"
COPY . .
WORKDIR "/src/LiturgiekStatistiek.Api"
RUN dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LiturgiekStatistiek.Api.dll"]
